#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4db47c2.name = "Upgrade from 4.3.2.6857~ynh1"
    test_upgrade_from.4db47c2.args.domain = "sub.domain.tld"
    test_upgrade_from.4db47c2.args.path = "/radarr"
    test_upgrade_from.4db47c2.args.admin = "package_checker"

    test_upgrade_from.bfacb2f5b9a3847ee0c3d2e13c59ab88425f8aca.name = "Upgrade from 5.18.4.9674~ynh1"
