test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4db47c2.name = "Upgrade from 4.3.2.6857~ynh1"
    test_upgrade_from.4db47c2.args.domain = "sub.domain.tld"
    test_upgrade_from.4db47c2.args.path = "/radarr"
    test_upgrade_from.4db47c2.args.admin = "package_checker"
