#!/bin/bash

source /usr/share/yunohost/helpers
#REMOVEME? ynh_abort_if_errors

data_dir=$(ynh_app_setting_get --key=data_dir)

run__external_authentication() {
    ynh_replace --match="<AuthenticationMethod>[[:alnum:]]*</AuthenticationMethod>" --replace="<AuthenticationMethod>External</AuthenticationMethod>" --file="$data_dir/config.xml"
}

ynh_app_config_run $1
