#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

ynh_config_add_logrotate
ynh_config_add_logrotate "$data_dir/logs"

yunohost service add $app --description="Radarr daemon" --log="$data_dir/logs/radarr.txt"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Configuring Radarr..."

api_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=api_key --value=$api_key

ynh_config_add --template="config.xml" --destination="$data_dir/config.xml"

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

# Build YunoHost multimedia directories
ynh_multimedia_build_main_dir

# Enable writing into these directories
ynh_multimedia_addaccess $app

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Application started" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
